### ISSUE TITLE
Quicksort worst case runtime can be O(n log n)

### ISSUE THREAD

**Issue by 983** [ericdrowell/BigOCheatSheet#98]
In [this issue](https://github.com/ericdrowell/BigOCheatSheet/pull/81), it was decided that quicksort worst case runtime is `O(n^2)` based on a paper which contained an assumption that leads to unnecessarily slow quicksort implementations. In my opinion, the cheat sheet should contain the running time of the asymptotically fastest implementation of each algorithm, which runs in `O(n log n)` in this case.

**Comment by chrislessard** [comment]
Actually, this is worth keeping as is. Assuming this is talking about randomized quicksort, it only performs that way on average, although there is still a (very small) possibility of the worst case O(n^2) occurring. It's important that this distinction - because Quicksort itself is random, random input doesn't actually make a difference to it. Once that aspect is lost, the worst case becomes very real. For more info see the CLRS, chapter 7 p. 174
